Repository learnforward2023/project-server, pull requests merged in 2024-03, with the labels that each got.

#1 Update Token for PR review
  .github/workflows/thank-you-for-create-pull-request.yaml
Labels: Please review

#3 Config: Project run multi-environment via Dockerfile
  Dockerfile
  package.json
Labels: feature

#4 Config: Add simple file to run CircleCI on main branch
  .circleci/config.yml
Labels: feature

#5 feat: config circle auto deploy to development
  .circleci/config.yml
Labels: Please review

#15 Feature/intruduce sequelize cli
  .env.development
  .env.example
  .env.production
  .eslintrc.js
  Dockerfile
  config/config.js
  database/index.ts
  index.ts
  models/index.ts
  package.json
  tsconfig.json
Labels: feature

#16 Feature/implement sign in api
  .eslintrc.js
  .sequelizerc
  index.ts
  migrations/20240317033336-create-user.js
  models/user.ts
  package.json
  routes/index.ts
  routes/users/index.ts
  routes/users/registerNewAccount.ts
  utils/constants.ts
Labels: Please review

#19 Feature/login with GitHub
  config/config.js
  deployment.yaml
  migrations/20240319120246-add_provideId_to_users.js
  models/user.ts
  package.json
  routes/users/index.ts
  routes/users/loginWithGithub.ts
  utils/constants.ts
Labels: Please review, feature

#26 Feat/apply sign in with google and facebook for multi environment
  config/config.js
  routes/users/index.ts
  routes/users/loginWithFacebook.ts
  routes/users/loginWithGoogle.ts
  utils/constants.ts
Labels: feature

#27 Feat/user login
  .eslintrc.js
  routes/users/index.ts
  routes/users/loginWithNormalAccount.ts
  routes/users/registerNewAccount.ts
Labels: feature
